# Generated by Django 2.2 on 2021-05-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('postcode', models.CharField(max_length=50)),
                ('neighboorhood', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=50)),
                ('aptNumber', models.CharField(max_length=50)),
                ('doorNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('roomStatus', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50)),
                ('customerLastName', models.CharField(max_length=50)),
                ('customerIdentityNumber', models.CharField(max_length=11)),
                ('customerPhoneNumber', models.CharField(max_length=20)),
                ('customerBirthDate', models.DateTimeField()),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateTimeField()),
                ('exitDate', models.DateTimeField()),
                ('bill', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Room')),
            ],
        ),
    ]
